apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockernewtestapplication
  namespace: default
  labels:
    app: dockernewtestapplication
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dockernewtestapplication
  template:
    metadata:
      labels:
        app: dockernewtestapplication
    spec:
      containers:
      - name: dockernewtestapplication-container-01
        image: recepcifter/webapplication5:latest
        ports:
        - containerPort: 6901
      nodeSelector:
        ost: win