kind: Pod
apiVersion: v1
metadata:
  name: foo-app
  labels:
    app: foo
spec:
  containers:
    - name: foo-app
      image: 'gcr.io/heptio-images/ks-guestbook-demo:0.2'
  nodeSelector:
    ostype: linux
